LOAD DATA
INFILE '../../prefile/TMP_REL'
APPEND
INTO TABLE tbl_tmp_mergerelareq_XXXXXXXX
(
	BANK    POSITION(1:8),
	LINENUM POSITION(9:16),
	ERRCODE POSITION(17:18),
	FLAG    POSITION(19:19),
	ISSBANK POSITION(20:27),
	IDTYPE  POSITION(28:29),
	IDNO    POSITION(30:49) "upper(:IDNO)",
	HISCARD POSITION(50:79)
)
